os: linux
sudo: false

# Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
# https://github.com/flutter/flutter/issues/6207
addons:
  apt:
    packages: [libstdc++6]
    # Specify sources otherwise we get the wrong version of libstdc++6
    sources: [ubuntu-toolchain-r-test]

cache:
  directories:
    - $HOME/.pub-cache

git: { depth: 2 }

env:
  global:
    - FLUTTER_BIN=$PWD/flutter/bin
    - FLUTTER=$FLUTTER_BIN/flutter
  matrix:
    - FLUTTER_BRANCH=stable
    - FLUTTER_BRANCH=dev

matrix:
  allow_failures:
    - env: FLUTTER_BRANCH=dev

install:
  - git clone https://github.com/flutter/flutter.git -b $FLUTTER_BRANCH
  - $FLUTTER doctor

script: ./travis.sh

# Only run Travis jobs for named branches (to avoid double builds for each PR)
branches:
  only: [master, /^\d\.x$/, /^\d-dev$/, /travis-build/]
