include: ../analysis_options.yaml

analyzer:
  strong-mode:
    implicit-dynamic: true

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: false 
    use_key_in_widget_constructors: false
