name: Flutter CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight

jobs:
  test:
    name: Test Flutter ${{ matrix.flutter_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - flutter_version: dev
            allow_failure: true
          - flutter_version: beta
            allow_failure: true
          - flutter_version: stable
            allow_failure: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.flutter_version }}
      - run: dart --version
      - run: flutter --version
      - name: Run travis
        run: ./travis.sh
        continue-on-error: ${{ matrix.allow_failure }}
